// my-qwik-app/src/components/starter/counter/counter.tsx
import { component$, useSignal, $ } from "@builder.io/qwik";
import styles from "./counter.module.css";
import Gauge from "../gauge";

export default component$(() => {
  const count = useSignal(0);

  const setCount = $((newValue: number) => {
    if (newValue < 0 || newValue > 100) {
      return;
    }
    count.value = newValue;
  });

  return (
    <div class={styles["counter-wrapper"]}>
      <button
        class="button-dark button-small"
        onClick$={() => setCount(count.value - 1)}
      >
        -
      </button>
      <Gauge value={count.value} />
      <button
        id="test-inc"
        class="button-dark button-small"
        onClick$={() => setCount(count.value + 1)}
      >
        +
      </button>
    </div>
  );
});

// rezact/src/components/Counter.tsx
export default function Counter() {
  let $counter = 0;

  return (
    <div>
      <h2 id="test-value">{$counter}</h2>

      <div>
        <button onClick={() => $counter--}>Dec</button>
        <button id="test-inc" onClick={() => $counter++}>
          Inc
        </button>
      </div>
    </div>
  );
}
