// solid-start/src/app.tsx
// @refresh reload
import { createSignal } from "solid-js";

import "./app.css";

export default function App() {
  const [count, setCount] = createSignal(0);

  return (
    <main>
      <h1>Hello world!</h1>

      <button
        id="test-inc"
        class="increment"
        onClick={() => setCount(count() + 1)}
      >
        Clicks: <span id="test-value">{count()}</span>
      </button>
      <p>
        Visit{" "}
        <a href="https://start.solidjs.com" target="_blank">
          start.solidjs.com
        </a>{" "}
        to learn how to build SolidStart apps.
      </p>
    </main>
  );
}

// preact/src/app.tsx
// import { useState } from "preact/hooks";
import Router from "preact-router";

export function Main() {
  return (
    <Router>
      <App path="/test" />
    </Router>
  );
}

export function App(_props: any) {
  // const [count, setCount] = useState(0);

  return (
    <>
      <h1>Hello World</h1>
      {/* <h2 id="test-value">{count}</h2>

      <div>
        <button id="test-inc" onClick={() => setCount((count) => count + 1)}>
          Inc
        </button>
      </div> */}
    </>
  );
}
